### ISSUE TITLE
Archives for Windows for 1.2.2 Invalid

### ISSUE THREAD

**Issue by vivace-io** [nosqlclient/nosqlclient#120] opened 2016-06-20 23:06 UTC
Attempting to extract a downloaded release for x86 and x64 versions using Window's built in .zip functionality results in an error notifying that the archive is invalid.

Extracting with 7zip works fine. I have not verified beyond current release.

I'm not entirely sure why, to be honest. And this could very well be something that's going over my head. But I thought I may bring it to your attention. Could maybe be an OS-related issue?

**Comment by rsercano** [comment] 2016-06-21 05:28
Hello,

it's definitely a OS related issue, due to long path names (after electron packaging) in ZIP file, windows default archiver doesn't allow to unzip it. But 7zip and winrar works fine as you mentioned. 

duplicate of #81 

Cheers

**Closed as completed** 2016-06-21 05:29 UTC
Labels: duplicate
