### ISSUE TITLE
Windows: Cannot find "electrify" on startup

### ISSUE THREAD

**Issue by cdechery** [nosqlclient/nosqlclient#322] opened 2017-02-22 17:23 UTC
The app won't even start and shows this error.

![image](https://cloud.githubusercontent.com/assets/5033136/23223644/59407be0-f90a-11e6-9203-6e24fdb80295.png)

Version 1.5 (downloaded just now) running on Windows 7

**Comment by rsercano** [comment] 2017-02-22 17:24
Hello @cdechery 

thanks for the feedback gotta check that asap.

**Comment by 3hertz** [comment] 2017-03-23 08:52
@cdechery @rsercano 
Same issue.
Was fixed when upacked in C:\

**Comment by rsercano** [comment] 2017-03-23 10:11
@3hertz 

Hi, thanks for the feedback, very soon I'm planning to release 2.0.0, hopefully it'll be fixed with that release, until then you can use [docker ](https://hub.docker.com/r/mongoclient/mongoclient/) build to see newest features. 

Sorry for the inconvenience.

**Comment by rsercano** [comment] 2017-04-09 15:37
Hello @cdechery 

can you please check again with the newest release ?

**Comment by kamranayub** [comment] 2017-05-30 20:59
Getting similar error with latest stable (2.1):

![image](https://cloud.githubusercontent.com/assets/563819/26604684/c6a7e05a-4550-11e7-94e4-47a6780c829e.png)

    Cannot find module 'shelljs'

Extracted to C:\mongoclient

OS: Windows 10 x64

**Comment by rsercano** [comment] 2017-05-31 05:34
Hello @kamranayub 

I'll check this asap, thanks for the feedback

**Comment by rsercano** [comment] 2017-06-08 12:26
Hi @kamranayub 

I've checked this in a few PCs with Windows 10 but couldn't reproduce. Are you sure you're downloading [this](https://github.com/mongoclient/mongoclient/releases/download/2.1.0/windows-portable-x64.zip)

Also please try to extract to `C:/` or `D:/` (main folders) directly, since path names a bit long that can be a trouble in windows.

**Closed as completed by rsercano** 2017-06-08 12:26 UTC

**Comment by kamranayub** [comment] 2017-06-12 17:24
Yeah it's definitely the same version:

![image](https://user-images.githubusercontent.com/563819/27046370-c46956d4-4f69-11e7-84bc-96011cff2757.png)

Might be an issue with how it gets extracted, I can try some more tests. Is it possible to roll up all these node_modules and have a flatter dependency structure?

**Comment by kamranayub** [comment] 2017-06-12 18:08
@rsercano yup that was it. Apparently default Windows extractor fails to extract all the necessary files. Using 7-zip to extract, the client works fine now. Thanks!

**Comment by rsercano** [comment] 2017-06-12 20:05
Great to hear that @kamranayub thanks for sharing resolution :)
