### ISSUE TITLE
Make scrollable only the content instead the entire container

### ISSUE THREAD

**Issue by gugadev** [nosqlclient/nosqlclient#261] opened 2016-12-21 15:38 UTC
The actual scroll behaviour is not very useful; when you scroll down to see the results or something else, the entire container is scrolled and the important sections are the sidebar, topbar (more menu) and the collection information (count, index count, etc.) are hidden. These sections must be always visible for easy access to important things, similar to Mongo Compass.

![](http://i.imgur.com/uWMOgdt.png)

I guess it could be solved adding a css rule to window container: `overflow: hidden` and the content `overflow: auto`.

**Comment by rsercano** [comment] 2016-12-21 15:43
Hi there,

this's already implemented in master branch and will be released very soon. Thanks for the feedback :)
duplicate of #247

**Closed as completed by rsercano** 2016-12-21 15:43 UTC
Labels: duplicate
