### ISSUE TITLE
Unziping the Windows x64 installer fails

### ISSUE THREAD

**Issue by sherry-ummen** [nosqlclient/nosqlclient#110] opened 2016-06-02 11:10 UTC
Whenever I try to download the app from https://github.com/rsercano/mongoclient/releases/download/1.2.1/windows-portable-x64.zip and try to unzip it . I get error "Compressed folder is invalid"

**Comment by rsercano** [comment] 2016-06-02 11:23
Hello, please try with 7zip or winrar, default windows archiver fails to unzip it. 
duplicate of #81

**Closed as completed by rsercano** 2016-06-02 11:23 UTC
Labels: duplicate

**Comment by sherry-ummen** [comment] 2016-06-02 11:28
Thanks that worked :+1:
