### ISSUE TITLE
Updating records seems to escape stored HTML strings

### ISSUE THREAD

**Issue by cmseaton42** [nosqlclient/nosqlclient#367] opened 2017-05-29 21:30 UTC
When I update a record in the client, HTML that I have stored is escaped which is not ideal and backlashes are added before quotes 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Mongoclient version used:
* Environment name (e.g. chrome 39, portable, docker):
* Operating System and version (e.g. windows 10, ubuntu 16, osx 10.12):

**Comment by rsercano** [comment] 2017-05-30 05:28
Hello  @cmseaton42 

thanks for the feedback, gotta check asap, would you mind sharing which version of mongoclient you're using right now ?

**Comment by cmseaton42** [comment] 2017-05-30 12:49
I am using v2.1.0.  Do you need any other information?

**Comment by rsercano** [comment] 2017-05-30 12:52
@cmseaton42 that's enough thank you so much, will check asap

**Comment by rsercano** [comment] 2017-06-04 07:57
Hello @cmseaton42 

I couldn't reproduce this properly, it puts **\n** for line breaks, is that what you mean ? If not could you please share an example document ?

**Comment by rsercano** [comment] 2017-06-16 10:02
I assume that's a won't fix issue please feel free to reopen it if you have an issue.

**Closed as completed by rsercano** 2017-06-16 10:02 UTC
Labels: bug, wontfix
