### ISSUE TITLE
Cannot add an array of documents

### ISSUE THREAD

**Issue by lluisd** [nosqlclient/nosqlclient#199] opened 2016-10-24 20:12 UTC
I've installed it and tried to insertMany or using the easy edit but it only inserts the last element of the array.

**Comment by rsercano** [comment] 2016-10-25 05:05
Hello,

thanks for the feedback, it's fixed in the brand new version. Gotta release it asap.

duplicate of #182 
Thank you so much.

**Closed as completed by rsercano** 2016-10-25 05:05 UTC
Labels: duplicate
