### ISSUE TITLE
node process using 100% of a CPU after a database connection

### ISSUE THREAD

**Issue by nmenetrier** [nosqlclient/nosqlclient#255] opened 2016-12-09 13:06 UTC
Hello,

We are running mongoclient 1.4.0 as a daemon on the same host as one of ours mongos daemons.
We noticed that just after a connection from mongoclient to our database, node process is using 100% of CPU time (only one CPU)

We tried to disable database statistics, we encountered the same issue.

```
Tasks: 105 total,   4 running, 101 sleeping,   0 stopped,   0 zombie
%Cpu(s): 49.2 us,  2.5 sy,  0.0 ni, 48.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  4047172 total,  1358088 free,   491832 used,  2197252 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2540276 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                           
19548 vitam     20   0 1213372 103624  12664 R 100.3  2.6  78:25.53 node

[vitam-iaas-mongos-01 ~]# ps -ef |grep node
vitam    19548     1 97 12:03 ?        01:21:54 /bin/node /vitam/bin/mongoclient/main.js
```

I don't find anything particular in journalctl --unit:
```
Dec 09 12:03:38 vitam-iaas-mongos-01 systemd[1]: Stopping Vitam Mongoclient...
Dec 09 12:03:38 vitam-iaas-mongos-01 systemd[1]: Started Vitam Mongoclient.
Dec 09 12:03:38 vitam-iaas-mongos-01 systemd[1]: Starting Vitam Mongoclient...
Dec 09 12:05:13 vitam-iaas-mongos-01 node[19548]: info: [connect] mongodb://vitamdb-admin:xxxxxxx@localhost:27017/logbook?authSource=admin connectTimeoutMS=3000, socketTimeoutMS=5000, sslValidate=false
Dec 09 12:05:14 vitam-iaas-mongos-01 node[19548]: info: [{"serverStatus":[]}] true
Dec 09 12:05:14 vitam-iaas-mongos-01 node[19548]: info: [{"serverStatus":[]}] true
Dec 09 12:05:15 vitam-iaas-mongos-01 node[19548]: info: [stats]
Dec 09 12:05:19 vitam-iaas-mongos-01 node[19548]: info: [{"serverStatus":[]}] true
Dec 09 12:05:22 vitam-iaas-mongos-01 node[19548]: info: [{"serverStatus":[]}] true
```

Do you have any idea about what can cause this issue ?
Or do you know how we can get more logs ?

Regards

**Comment by rsercano** [comment] 2016-12-09 13:13
Hello,

thanks for the feedback, gotta find a workaround for that, I just remember there're some similar reports for meteor itself. I guess that's where it comes, gotta check that.

Cheers

**Comment by nmenetrier** [comment] 2016-12-09 16:20
Our meteor version: Meteor 1.4.2.3

**Comment by rsercano** [comment] 2016-12-10 19:23
Hi again,

I tried to reproduce this but, couldn't have done either in linux or windows, having said that though, I saw a few bug reports about that in meteor itself, but as far as I see it seems to be fixed in 1.4.2.3 and shouldn't have such a behaviour, can it be related with your OS, or how you setup and use mongoclient ?

**Comment by rsercano** [comment] 2016-12-10 19:26
Additionally you can take a look at [here](https://github.com/meteor/meteor/issues/7491)

**Comment by nmenetrier** [comment] 2016-12-12 14:13
Ok thanks I think I understand, we builded our rpm file with meteor 1.4.2.1...
I'll try with the last meteor version.
Thanks a lot for your help.

**Comment by rsercano** [comment] 2016-12-12 14:16
Hope you can solve it, with newest version

**Closed as completed by rsercano** 2016-12-12 14:16 UTC
Labels: potential bug

**Comment by nmenetrier** [comment] 2016-12-15 10:50
We finally found what was causing the issue.
We was still having the issue while packaging our rpm with meteor 1.4.2.3.
But our server was using node v4.6.1 while meteor 1.4.2.3 is using node v4.6.2.
With node v4.6.2 the issue has been solved. :)

**Comment by rsercano** [comment] 2016-12-15 10:56
Great news thanks for sharing :)
