### ISSUE TITLE
windows download zip file error

### ISSUE THREAD

**Issue by nukkamoto** [nosqlclient/nosqlclient#121] opened 2016-06-27 09:32 UTC
I cannot extract the zip folder on win 10.

> windows cannot open the folder the compressed zipped folder is invalid

I looked around I think the problem could be as described on this article.

http://superuser.com/questions/463881/the-compressed-zip-folder-is-invalid-or-corrupted-error-after-downloading-zi

> I had the same issue - created a .zip on a Mac that resulted in an error on Windows 7 (but extracted properly on the Mac).
> 
> Following his hint, I noticed that I have a bunch of folders with a bullet in the name (option-8 on the Mac keyboard). Removed all those folders, re-zipped and presto - the .zip file works without issue on Windows.
> 
> So, apparently, using characters that are illegal in Windows in the filenames contained in the zip-file will cause Windows to report the "the compressed (zipped) file XYZXYZ is invalid" error with opening the .zip file.

**Comment by rsercano** [comment] 2016-06-27 10:06
Hello,

the problem is about long path names, you can simply use 7zip or winrar to extract it default archiver doesn't allow you to do so.

duplicate of #81 

Cheers

**Closed as completed by rsercano** 2016-06-27 10:06 UTC
Labels: duplicate
