### ISSUE TITLE
Windows zip files are corrupt

### ISSUE THREAD

**Issue by mosheka** [nosqlclient/nosqlclient#137] opened 2016-07-19 13:40 UTC
Both 64 and 32 bits return the following error after download:
Windows cannot open the folder
The compressed (zipped) Folder ... is invalid

**Comment by rsercano** [comment] 2016-07-19 14:29
Hi there, 

please use winrar or 7zip to unzip it. 

duplicate of #81

**Closed as completed by rsercano** 2016-07-19 14:29 UTC
Labels: wontfix
