### ISSUE TITLE
Button to submit query spins forever before even finishing typing the query

### ISSUE THREAD

**Issue by dandv** [nosqlclient/nosqlclient#498] opened 2019-04-09 02:33 UTC
Continuing here the discussion from #495.

## Current Behavior

Try simply connecting to `mongodb://agendan:nuam0agenda@ds052408.mlab.com:52408/agenda` several times. (It's a demo DB on mLab, so it's OK that the password is exposed here, as long as nobody changes it). Most of the times, this works, but sometimes it doesn't. Here's one instance:

![image](https://user-images.githubusercontent.com/33569/55769221-90cb5a00-5a45-11e9-94ce-afb900b0d5f6.png)

Docker log shows
> {"connectionUrl":"mongodb://agendan:nuam0agenda@ds052408.mlab.com:52408/","options":{"useNewUrlParser":true,"authSource":"agenda"},"sessionId":"qsBCsmjZsmLRZBB7h","level":"debug","message":"[connect]"}
{"sessionLength":"8","level":"info","message":"[connect]"}
{"methodArray":[{"serverStatus":[]}],"runOnAdminDB":true,"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}
{"externalError":"not authorized on admin to execute command { serverStatus: 1, $clusterTime: { clusterTime: Timestamp(1554776999, 2), signature: { hash: BinData(0, 3CF6EF754B0CE05B07703A165ADB479C831F8287), keyId: 6618350754082062337 } }, lsid: { id: UUID(\"0a3b5adf-3c06-4957-aed1-cac80e937a75\") }, $db: \"admin\" }","methodArray":[{"serverStatus":[null]}],"runOnAdminDB":true,"sessionId":"qsBCsmjZsmLRZBB7h","level":"error","message":"[query-error]"}
{"methodArray":[{"executeDbAdminCommand":[{"top":1},{}]}],"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}
{"externalError":"not authorized on admin to execute command { top: 1, $clusterTime: { clusterTime: Timestamp(1554776999, 3), signature: { hash: BinData(0, 3CF6EF754B0CE05B07703A165ADB479C831F8287), keyId: 6618350754082062337 } }, lsid: { id: UUID(\"0a3b5adf-3c06-4957-aed1-cac80e937a75\") }, $db: \"admin\" }","methodArray":[{"executeDbAdminCommand":[{"top":1},{"readPreference":null},null]}],"sessionId":"qsBCsmjZsmLRZBB7h","level":"error","message":"[query-error]"}
{"methodArray":[{"serverStatus":[]}],"runOnAdminDB":true,"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}
{"externalError":"not authorized on admin to execute command { serverStatus: 1, $clusterTime: { clusterTime: Timestamp(1554776999, 5), signature: { hash: BinData(0, 3CF6EF754B0CE05B07703A165ADB479C831F8287), keyId: 6618350754082062337 } }, lsid: { id: UUID(\"0a3b5adf-3c06-4957-aed1-cac80e937a75\") }, $db: \"admin\" }","methodArray":[{"serverStatus":[null]}],"runOnAdminDB":true,"sessionId":"qsBCsmjZsmLRZBB7h","level":"error","message":"[query-error]"}
{"methodArray":[{"executeDbAdminCommand":[{"top":1},{}]}],"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}
{"externalError":"not authorized on admin to execute command { top: 1, $clusterTime: { clusterTime: Timestamp(1554776999, 5), signature: { hash: BinData(0, 3CF6EF754B0CE05B07703A165ADB479C831F8287), keyId: 6618350754082062337 } }, lsid: { id: UUID(\"0a3b5adf-3c06-4957-aed1-cac80e937a75\") }, $db: \"admin\" }","methodArray":[{"executeDbAdminCommand":[{"top":1},{"readPreference":null},null]}],"sessionId":"qsBCsmjZsmLRZBB7h","level":"error","message":"[query-error]"}
{"methodArray":[{"stats":[]}],"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}
{"methodArray":[{"serverStatus":[]}],"runOnAdminDB":true,"sessionId":"qsBCsmjZsmLRZBB7h","level":"info","message":"[admin-query-execution]"}

For my production databases (7 collections, but some of them with 50,000+ and 500,000+ documents), I always get the spinning button.

## Your Environment
* Nosqlclient version used: About shows "Open Source Edition - Version 2.2.0" but that's been the case for over a year, so I don't know what to put here.
* Environment name: Docker, Chrome 73
* Operating System and version: Ubuntu 18

**Comment by rsercano** [comment] 2019-04-09 06:12
This seems pretty hard to reproduce, can you confirm that you always encounter with this when there're error logs shown in the #495 ?

**Comment by rsercano** [comment] 2019-04-09 06:51
**Update;** I'm sure that's not related with console logs, this can be related with not disconnecting properly for previous connections. Do you use `disconnect` button which is encouraged to do per your disconnection ? 

On browser refreshes, the existing connections would be still alive until it becomes **idle** (which takes a lot of time). I'm now looking for a convenient way to disconnect from them on browser refresh, but in the meantime would you please try to use disconnect button and tell me if that works out for you ?

Also you can disable `fetching DB stats` on **settings** to prevent immediate querying to the database which's already meaningless for you since you don't have required permissions on `admin` database.

**Comment by rsercano** [comment] 2019-04-09 07:35
Just added the `beforeunload` event to disconnect on page refreshes, would you please retry this after pulling in approx. 15 minutes @dandv ?

**Comment by rsercano** [comment] 2019-04-16 07:29
Since it's been a week with no activity I'm closing this issue please feel free to re-open @dandv

**Comment by nicohell** [comment] 2019-04-19 17:21
Get same issue on a Linux Centos 7 systemd install with MongoDB 4.0.9

Below are console messages just after connection + collection's selection +  button refresh click ; After that datas are displayed but  I can not save any modifications (No result found to save) 
 
> app.js?hash=8e32cb00b4e7321247426d98eaa348ba074eec7a:38248 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
> (anonymous) @ app.js?hash=8e32cb00b4e7321247426d98eaa348ba074eec7a:38248
> modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:7487 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0b.woff2
> modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:7487 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:3000/packages/fortawesome_fontawesome/upstream/fonts/fontawesome-webfont.woff2?v=4.7.0
> modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:7487 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2
> modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:10712 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost:3000/packages/twbs_bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
> 2meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 Exception in delivering result of invoking 'find': TypeError: Cannot read property 'mData' of undefined
>     at HTMLTableCellElement.<anonymous> (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82590)
>     at Function.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1416)
>     at jQuery.fn.init.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1188)
>     at HTMLTableElement.<anonymous> (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82587)
>     at Function.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1416)
>     at jQuery.fn.init.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1188)
>     at jQuery.fn.init.DataTable [as dataTable] (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82288)
>     at jQuery.fn.init.$.fn.DataTable (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:96542)
>     at Object.setGridEditorValue (index.js:310)
>     at QueryRender.setResultToEditors (render.js:202)

**Comment by rsercano** [comment] 2019-04-19 17:27
This seems like another issue @nicohell will check it in detail tomorrow,

**Comment by rsercano** [comment] 2019-04-19 17:39
The only error I can relate this with is;

```
2meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1061 Exception in delivering result of invoking 'find': TypeError: Cannot read property 'mData' of undefined
at HTMLTableCellElement. (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82590)
at Function.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1416)
at jQuery.fn.init.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1188)
at HTMLTableElement. (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82587)
at Function.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1416)
at jQuery.fn.init.each (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:1188)
at jQuery.fn.init.DataTable [as dataTable] (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:82288)
at jQuery.fn.init.$.fn.DataTable (modules.js?hash=c6dc3b4fa2574ad84714ff03ac790ae7e74512f1:96542)
at Object.setGridEditorValue (index.js:310)
at QueryRender.setResultToEditors (render.js:202)
```

But I couldn't reproduce this @nicohell, could you please be more specific with your details, were there any data in your collection ? Did you just click refresh button or click find too and in which order ?

**Comment by nicohell** [comment] 2019-04-19 17:54
Here is a link to a vido showing exact manipulations : [https://dev.logilibres.org/public/nosqlclient.mp4](url)
After a while, Execute button comes back but "nosqlClient" says that we need to refresh collections because connection has been lost.

**Comment by rsercano** [comment] 2019-04-19 18:02
Ah thanks, now I got the issue I guess, there's an HTML content in your data, probably that's the main issue because a PR for populating the datatable for result view was creating HTML on the fly, there's probably a conflict within it. Probably tomorrow it would be fixed, tonight I don't have time :/, sorry for the inconvenience .

**Comment by nicohell** [comment] 2019-04-19 18:09
Ok tomorrow is Saturday, Monday is public holiday here in France, so If you found the issue, correction could wait Tuesday :-)
Thanks for your ractivity.

**Comment by rsercano** [comment] 2019-04-20 09:22
@nicohell hopefully this's fixed within https://github.com/nosqlclient/nosqlclient/commit/29026caad260be220c6dc7fa718156cff485858c but feel free to raise another issue if you encounter this again.

**Closed as completed** 2019-04-20 09:21 UTC

**Comment by nicohell** [comment] 2019-04-24 12:29
Display is fixed but recording still not working ; See vidéo  :  https://dev.logilibres.org/public/nosqlclient_save.mp4

Le 20/04/2019 11:22, Sercan Özdemir a écrit :

> @nicohell [1] hopefully this's fixed within 29026ca [2] but feel free to raise another issue if you encounter this again. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].


Links:
------
[1] https://github.com/nicohell
[2]
https://github.com/nosqlclient/nosqlclient/commit/29026caad260be220c6dc7fa718156cff485858c
[3]
https://github.com/nosqlclient/nosqlclient/issues/498#issuecomment-485076900
[4]

**Comment by rsercano** [comment] 2019-04-24 13:17
If there's no sensitive data would you please share the HTML which is shown in your video ? I would like to reproduce this on my side. @nicohell

**Comment by rsercano** [comment] 2019-04-24 13:18
Let's continue to discuss this on #503
